allianceauth/timerboard/urls.py
from django.urls import path

from . import views

app_name = 'timerboard'

urlpatterns = [
    path('', views.TimerView.as_view(), name='view'),
    path('add/', views.AddTimerView.as_view(), name='add'),
    path('remove/<int:pk>/', views.RemoveTimerView.as_view(), name='delete'),
    path('edit/<int:pk>/', views.EditTimerView.as_view(), name='edit'),
]

allianceauth/urls.py
from typing import List, Iterable, Callable

from django.urls import include
import esi.urls
from django.conf import settings
from django.contrib import admin
from django.urls import URLPattern, include, path
from django.views.generic.base import TemplateView

import allianceauth.authentication.urls
import allianceauth.authentication.views
import allianceauth.groupmanagement.urls
import allianceauth.notifications.urls
import allianceauth.services.urls
from allianceauth import NAME, views
from allianceauth.authentication import hmac_urls
from allianceauth.authentication.decorators import (
    decorate_url_patterns,
    main_character_required
)
from allianceauth.hooks import get_hooks

admin.site.site_header = NAME


def urls_from_apps(
    apps_hook_functions: Iterable[Callable], public_views_allowed: List[str]
) -> List[URLPattern]:
    """Return urls from apps and add default decorators."""

    url_patterns = []
    allowed_apps = set(public_views_allowed)
    for app_hook_function in apps_hook_functions:
        url_hook = app_hook_function()
        app_pattern = url_hook.include_pattern
        excluded_views = (
            url_hook.excluded_views
            if app_pattern.app_name in allowed_apps
            else None
        )
        url_patterns += [
            path(
                "",
                decorate_url_patterns(
                    [app_pattern], main_character_required, excluded_views
                )
            )
        ]

    return url_patterns


# Functional/Untranslated URL's
urlpatterns = [
    # Locale
    path('i18n/', include('django.conf.urls.i18n')),

    # Authentication
    path('', include(allianceauth.authentication.urls)),
    path('account/login/', TemplateView.as_view(template_name='public/login.html'), name='auth_login_user'),
    path('account/', include(hmac_urls)),

    # Admin urls
    path('admin/', admin.site.urls),

    # SSO
    path('sso/', include((esi.urls, 'esi'), namespace='esi')),
    path('sso/login', allianceauth.authentication.views.sso_login, name='auth_sso_login'),

    # Notifications
    path('', include(allianceauth.notifications.urls)),

    # Groups
    path('', include(allianceauth.groupmanagement.urls)),

    # Services
    path('', decorate_url_patterns(allianceauth.services.urls.urlpatterns, main_character_required)),

    # Night mode
    path('night/', views.NightModeRedirectView.as_view(), name='nightmode'),

    # Theme Change
    path('theme/', views.ThemeRedirectView.as_view(), name='theme')
]

url_hooks = get_hooks("url_hook")
public_views_allows = getattr(settings, "APPS_WITH_PUBLIC_VIEWS", [])
urlpatterns += urls_from_apps(url_hooks, public_views_allows)

allianceauth/timerboard/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils.translation import gettext_lazy as _

from allianceauth.eveonline.models import EveCharacter
from allianceauth.eveonline.models import EveCorporationInfo


class Timer(models.Model):
    class Objective(models.TextChoices):
        """
        Choices for Objective Type
        """

        FRIENDLY = "Friendly", _("Friendly")
        HOSTILE = "Hostile", _("Hostile")
        NEUTRAL = "Neutral", _("Neutral")

    class Structure(models.TextChoices):
        """
        Choices for Structure Type
        """

        POCO = "POCO", _("POCO")
        ORBITALSKYHOOK = "Orbital Skyhook", _("Orbital Skyhook")
        IHUB = "I-HUB", _("Sovereignty Hub")
        TCU = "TCU", _("TCU")  # Pending Remval
        POSS = "POS[S]", _("POS [S]")
        POSM = "POS[M]", _("POS [M]")
        POSL = "POS[L]", _("POS [L]")
        ASTRAHUS = "Astrahus", _("Astrahus")
        FORTIZAR = "Fortizar", _("Fortizar")
        KEEPSTAR = "Keepstar", _("Keepstar")
        RAITARU = "Raitaru", _("Raitaru")
        AZBEL = "Azbel", _("Azbel")
        SOTIYO = "Sotiyo", _("Sotiyo")
        ATHANOR = "Athanor", _("Athanor")
        TATARA = "Tatara", _("Tatara")
        PHAROLUX = "Pharolux Cyno Beacon", _("Cyno Beacon")
        TENEBREX = "Tenebrex Cyno Jammer", _("Cyno Jammer")
        ANSIBLEX = "Ansiblex Jump Gate", _("Ansiblex Jump Gate")
        MERCDEN = "Mercenary Den", _("Mercenary Den")
        MOONPOP = "Moon Mining Cycle", _("Moon Mining Cycle")
        METENOX = "Metenox Moon Drill", _("Metenox Moon Drill")
        OTHER = "Other", _("Other")

    class TimerType(models.TextChoices):
        """
        Choices for Timer Type
        """

        UNSPECIFIED = "UNSPECIFIED", _("Not Specified")
        SHIELD = "SHIELD", _("Shield")
        ARMOR = "ARMOR", _("Armor")
        HULL = "HULL", _("Hull")
        FINAL = "FINAL", _("Final")
        ANCHORING = "ANCHORING", _("Anchoring")
        UNANCHORING = "UNANCHORING", _("Unanchoring")
        ABANDONED = "ABANDONED", _("Abandoned")

    details = models.CharField(max_length=254, default="")
    system = models.CharField(max_length=254, default="")
    planet_moon = models.CharField(max_length=254, blank=True, default="")
    structure = models.CharField(max_length=254,choices=Structure.choices,default=Structure.OTHER)
    timer_type = models.CharField(max_length=254,choices=TimerType.choices,default=TimerType.UNSPECIFIED)
    objective = models.CharField(max_length=254, choices=Objective.choices, default=Objective.NEUTRAL)
    eve_time = models.DateTimeField()
    important = models.BooleanField(default=False)
    eve_character = models.ForeignKey(EveCharacter, null=True, on_delete=models.SET_NULL)
    eve_corp = models.ForeignKey(EveCorporationInfo, on_delete=models.CASCADE)
    corp_timer = models.BooleanField(default=False)
    user = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)

    def __str__(self) -> str:
        return str(self.system) + ' ' + str(self.details)

    class Meta:
        ordering = ['eve_time']

allianceauth/timerboard/views.py
import logging

from django.contrib import messages
from django.contrib.auth.mixins import (
    LoginRequiredMixin,
    PermissionRequiredMixin,
)
from django.db.models import Q
from django.shortcuts import get_object_or_404, render
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django.views import View
from django.views.generic import CreateView, DeleteView, UpdateView

from allianceauth.eveonline.models import EveCorporationInfo
from allianceauth.timerboard.form import TimerForm
from allianceauth.timerboard.models import Timer

logger = logging.getLogger(__name__)

TIMER_VIEW_PERMISSION = "auth.timer_view"
TIMER_MANAGE_PERMISSION = "auth.timer_management"


class BaseTimerView(LoginRequiredMixin, PermissionRequiredMixin, View):
    pass


class TimerView(BaseTimerView):
    template_name = "timerboard/view.html"
    permission_required = TIMER_VIEW_PERMISSION

    def get(self, request):
        """
        Renders the timer view

        :param request:
        :type request:
        :return:
        :rtype:
        """

        def get_bg_modifier(structure):
            """
            Returns the bootstrap bg modifier for the given structure

            :param structure:
            :type structure:
            :return:
            :rtype:
            """

            if structure in bg_info:
                return "info"
            elif structure in bg_warning:
                return "warning"
            elif structure in bg_danger:
                return "danger"
            elif structure in bg_secondary:
                return "secondary"

            return "primary"

        logger.debug(f"timer_view called by user {request.user}")
        char = request.user.profile.main_character

        if char:
            corp = char.corporation
        else:
            corp = None

        base_query = Timer.objects.select_related("eve_character")

        timers = []
        corp_timers = []
        future_timers = []
        past_timers = []

        bg_info = [
            Timer.Structure.POCO.value,  # POCO
            Timer.Structure.POSS.value,  # POS[S]
            Timer.Structure.POSM.value,  # POS[M]
            Timer.Structure.POSL.value,  # POS[L]
        ]
        bg_warning = [
            Timer.Structure.ANSIBLEX.value,  # Ansiblex Jump Gate
            Timer.Structure.ATHANOR.value,  # Athanor
            Timer.Structure.AZBEL.value,  # Azbel
            Timer.Structure.MERCDEN.value,  # Mercenary Den
            Timer.Structure.METENOX.value,  # Metenox Moon Drill
            Timer.Structure.ORBITALSKYHOOK.value,  # Orbital Skyhook
            Timer.Structure.PHAROLUX.value,  # Pharolux Cyno Beacon
            Timer.Structure.RAITARU.value,  # Raitaru
            "Station",  # Legacy structure, remove in future update
            Timer.Structure.TATARA.value,  # Tatara
            Timer.Structure.TENEBREX.value,  # Tenebrex Cyno Jammer
        ]
        bg_danger = [
            Timer.Structure.ASTRAHUS.value,  # Astrahus
            Timer.Structure.FORTIZAR.value,  # Fortizar
            Timer.Structure.IHUB.value,  # I-HUB
            Timer.Structure.KEEPSTAR.value,  # Keepstar
            Timer.Structure.SOTIYO.value,  # Sotiyo
            Timer.Structure.TCU.value,  # TCU (Legacy structure, remove in future update)
        ]
        bg_secondary = [
            Timer.Structure.MOONPOP.value,  # Moon Mining Cycle
            Timer.Structure.OTHER.value,  # Other
        ]

        # Timers
        for timer in base_query.filter(corp_timer=False):
            timer.bg_modifier = get_bg_modifier(timer.structure)
            timers.append(timer)

        # Corp Timers
        for timer in base_query.filter(corp_timer=True, eve_corp=corp):
            timer.bg_modifier = get_bg_modifier(timer.structure)
            corp_timers.append(timer)

        # Future Timers
        for timer in base_query.filter(corp_timer=False, eve_time__gte=timezone.now()):
            timer.bg_modifier = get_bg_modifier(timer.structure)
            future_timers.append(timer)

        # Past Timers
        for timer in base_query.filter(corp_timer=False, eve_time__lt=timezone.now()):
            timer.bg_modifier = get_bg_modifier(timer.structure)
            past_timers.append(timer)

        render_items = {
            "timers": timers,
            "corp_timers": corp_timers,
            "future_timers": future_timers,
            "past_timers": past_timers,
        }

        return render(request, self.template_name, context=render_items)


class TimerManagementView(BaseTimerView):
    permission_required = TIMER_MANAGE_PERMISSION
    index_redirect = "timerboard:view"
    success_url = reverse_lazy(index_redirect)
    model = Timer

    def get_timer(self, timer_id):
        return get_object_or_404(self.model, id=timer_id)


class AddUpdateMixin:
    def get_form_kwargs(self):
        """
        Inject the request user into the kwargs passed to the form
        """
        kwargs = super().get_form_kwargs()
        kwargs.update({"user": self.request.user})
        return kwargs


class AddTimerView(TimerManagementView, AddUpdateMixin, CreateView):
    template_name_suffix = "_create_form"
    form_class = TimerForm

    def form_valid(self, form):
        result = super().form_valid(form)
        timer = self.object
        logger.info(
            f"Created new timer in {timer.system} at {timer.eve_time} by user {self.request.user}"
        )
        messages.success(
            self.request,
            _("Added new timer in %(system)s at %(time)s.")
            % {"system": timer.system, "time": timer.eve_time},
        )
        return result


class EditTimerView(TimerManagementView, AddUpdateMixin, UpdateView):
    template_name_suffix = "_update_form"
    form_class = TimerForm

    def form_valid(self, form):
        messages.success(self.request, _("Saved changes to the timer."))
        return super().form_valid(form)


class RemoveTimerView(TimerManagementView, DeleteView):
    pass


def dashboard_timers(request):
    if request.user.has_perm(TIMER_VIEW_PERMISSION):
        try:
            corp = request.user.profile.main_character.corporation
        except (EveCorporationInfo.DoesNotExist, AttributeError):
            return ""

        timers = Timer.objects.select_related("eve_character").filter(
            (Q(corp_timer=True) & Q(eve_corp=corp)) | Q(corp_timer=False),
            eve_time__gte=timezone.now(),
        )[:5]

        if timers.count():
            context = {
                "timers": timers,
            }

            return render_to_string(
                template_name="timerboard/dashboard.timers.html",
                context=context,
                request=request,
            )
        else:
            return ""
    else:
        return ""

allianceauth/timerboard/templates/timerboard/dashboard.timers.html
{% load i18n %}
{% load evelinks %}

<div class="col-12 mb-3">
    <div class="card h-100">
        <div class="card-body">
            {% translate "Upcoming Timers" as widget_title %}
            {% include "framework/dashboard/widget-title.html" with title=widget_title %}

            <div>
                <table class="table">
                    <thead>
                        <tr>
                            <th class="text-center">{% translate "Details" %}</th>
                            <th class="text-center">{% translate "Timer" %}</th>
                            <th class="text-center">{% translate "Type" %}</th>
                            <th class="text-center">{% translate "System" %}</th>
                            <th class="text-center">{% translate "EVE Time" %}</th>
                        </tr>
                    </thead>

                    <tbody>
                        {% for timer in timers %}
                            <tr>
                                <td class="text-center">
                                    {{ timer.details }}
                                </td>
                                <td class="text-center">
                                    {{ timer.get_timer_type_display }}
                                </td>
                                <td class="text-center" nowrap>
                                    {% if timer.objective == "Hostile" %}
                                        <div class="badge bg-danger">
                                            {% translate "Hostile" %}
                                        </div>
                                    {% endif %}
                                    {% if timer.objective == "Friendly" %}
                                        <div class="badge bg-primary">
                                            {% translate "Friendly" %}
                                        </div>
                                    {% endif %}
                                    {% if timer.objective == "Neutral" %}
                                        <div class="badge bg-secondary">
                                            {% translate "Neutral" %}
                                        </div>
                                    {% endif %}
                                </td>
                                <td class="text-center"><a href="{{ timer.system|dotlan_solar_system_url }}">
                                    {{ timer.system }} {{ timer.planet_moon }}
                                    </a>
                                </td>
                                <td class="text-center" nowrap>{{ timer.eve_time | date:"Y-m-d H:i" }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

allianceauth/timerboard/templates/timerboard/form.html
{% extends "allianceauth/base-bs5.html" %}

{% load django_bootstrap5 %}
{% load i18n %}

{% block page_title %}
{% endblock page_title %}

{% block header_nav_brand %}
    {% translate "Structure Timers" %}
{% endblock header_nav_brand %}

{% block content %}
    <div>
        <h1 class="page-header text-center mb-3">
            {% block page_header %}
            {% endblock page_header %}
        </h1>

        {% include "timerboard/index_button.html" %}

        <div class="card card-primary border-0">
            <div class="card-header">
                <div class="card-title mb-0">
                    {% translate "Structure Timer Details" %}
                </div>
            </div>

            <div class="card-body">
                <div class="row justify-content-center">
                    <div class="col-md-6">
                        <form id="add-timer-form" role="form" action="" method="POST">
                            {% csrf_token %}

                            {% bootstrap_form form %}

                            <div class="form-group mt-3 clearfix">
                                <button class="btn btn-primary" type="submit">
                                    {% block submit_button_text %}
                                    {% endblock submit_button_text %}
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

{% block extra_javascript %}
    {% include 'bundles/jquery-datetimepicker-js.html' %}

    <script>
        $(document).ready(() => {
            $('#id_start').datetimepicker({
                setlocale: '{{ LANGUAGE_CODE }}',
                mask: true,
                format: 'Y-m-d H:i',
                minDate: 0
            });
        });
    </script>
{% endblock %}

allianceauth/timerboard/templates/timerboard/index_button.html
{% load i18n %}

<div class="text-end mb-3">
    <a href="{% url 'timerboard:view' %}" class="btn btn-secondary">{% translate "Back" %}</a>
</div>

allianceauth/timerboard/templates/timerboard/timer_confirm_delete.html
{% extends "allianceauth/base-bs5.html" %}

{% load i18n %}

{% block page_title %}
    {% translate "Delete Timer" %}
{% endblock page_title %}

{% block header_nav_brand %}
    {% translate "Structure Timers" %}
{% endblock header_nav_brand %}

{% block content %}
    <div>
        {% translate "Delete Timer" as page_header %}
        {% include "framework/header/page-header.html" with title=page_header %}

        {% include "timerboard/index_button.html" %}

        <div class="row justify-content-center">
            <div class="col-md-4">
                <div class="row">
                    <form action="" method="post">
                        {% csrf_token %}

                        <p>{% blocktranslate %}Are you sure you want to delete timer "{{ object }}"?{% endblocktranslate %}</p>

                        <input class="btn btn-danger btn-block" type="submit" value="Confirm">
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

allianceauth/timerboard/templates/timerboard/timer_create_form.html
{% extends "timerboard/form.html" %}
{% load i18n %}

{% block page_title %}
    {% translate "Create Timer" %}
{% endblock page_title %}

{% block page_header %}
    {% translate "Create Structure Timer" %}
{% endblock %}

{% block submit_button_text %}
    {% translate "Create Timer" %}
{% endblock %}

{% block extra_javascript %}
    {% include 'bundles/timerboard-js.html' %}
    {% include 'bundles/jquery-datetimepicker-js.html' %}
    {% include 'bundles/jquery-datetimepicker-css.html' %}

    <script>
        $(document).ready(() => {
            $('input#id_absolute_time').datetimepicker({
                setlocale: '{{ LANGUAGE_CODE }}',
                format: 'Y-m-d H:i',
                minDate: 0,
                defaultDate: null
            });
        });
    </script>
{% endblock %}

allianceauth/timerboard/templates/timerboard/timer_update_form.html
{% extends "timerboard/form.html" %}
{% load i18n %}

{% block page_title %}
    {% translate "Update Structure Timer" %}
{% endblock page_title %}

{% block page_header %}
    {% translate "Update Structure Timer" %}
{% endblock %}

{% block submit_button_text %}
    {% translate "Update Structure Timer" %}
{% endblock %}

{% block extra_javascript %}
    {% include 'bundles/timerboard-js.html' %}
    {% include 'bundles/jquery-datetimepicker-js.html' %}
    {% include 'bundles/jquery-datetimepicker-css.html' %}

    <script>
        $(document).ready(() => {
            $('input#id_absolute_time').datetimepicker({
                setlocale: '{{ LANGUAGE_CODE }}',
                mask: true,
                format: 'Y-m-d H:i',
                defaultDate: null
            });
        });
    </script>
{% endblock %}

allianceauth/timerboard/templates/timerboard/timertable.html
{% load evelinks %}
{% load i18n %}

<div class="table-responsive">
    <table class="table" id="{{ id }}">
        <thead>
            <tr>
                <th class="text-center">{% translate "Details" %}</th>
                <th class="text-center">{% translate "Objective" %}</th>
                <th class="text-center">{% translate "System" %}</th>
                <th class="text-center">{% translate "Structure" %}</th>
                <th class="text-center">{% translate "Eve Time" %}</th>
                <th class="text-center">{% translate "Local Time" %}</th>
                <th class="text-center">{% translate "Creator" %}</th>

                {% if perms.auth.timer_management %}
                    <th class="text-center">{% translate "Action" %}</th>
                {% endif %}
            </tr>
        </thead>

        <tbody>
            {% for timer in timers %}
                <tr class="{% if timer.important == True %}bg-danger bg-opacity-25{% else %}bg-info bg-opacity-25{% endif %}">
                    <td style="width: 150px;" class="text-center">
                        {{ timer.details }}

                        {% if timer.timer_type != 'UNSPECIFIED' %}
                            <br />
                            ({{ timer.get_timer_type_display }})
                        {% endif %}
                    </td>

                    <td class="text-center">
                        {% comment %} Objective: Hostile (BG: Danger) {% endcomment %}
                        {% if timer.objective == "Hostile" %}
                            <div class="badge bg-danger">

                        {% comment %} Objective: Friendly (BG: Primare) {% endcomment %}
                        {% elif timer.objective == "Friendly" %}
                            <div class="badge bg-primary">

                        {% comment %} Objective: Neutral (BG: Secondary) {% endcomment %}
                        {% elif timer.objective == "Neutral" %}
                            <div class="badge bg-secondary">
                        {% endif %}

                            {{ timer.get_objective_display }}
                        </div>
                    </td>

                    <td class="text-center">
                        <a href="{{ timer.system|dotlan_solar_system_url }}">{{ timer.system }} {{ timer.planet_moon }}</a>
                    </td>

                    <td class="text-center">
                        <div class="badge bg-{{ timer.bg_modifier }}">
                            {{ timer.get_structure_display }}
                        </div>
                    </td>

                    <td class="text-center" nowrap>{{ timer.eve_time | date:"Y-m-d H:i" }}</td>

                    <td class="text-center" nowrap>
                        <div id="localtime{{ timer.id }}"></div>
                        <div id="countdown{{ timer.id }}"></div>
                    </td>

                    <td class="text-center">{{ timer.eve_character.character_name }}</td>

                    {% if perms.auth.timer_management %}
                        <td class="text-center">
                            <a href="{% url 'timerboard:delete' timer.id %}" class="btn btn-danger">
                                <i class="fa-solid fa-trash-can fa-fw"></i>
                            </a>
                            <a href="{% url 'timerboard:edit' timer.id %}" class="btn btn-info">
                                <i class="fa-solid fa-pen-to-square fa-fw"></i>
                            </a>
                        </td>
                    {% endif %}
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

allianceauth/timerboard/templates/timerboard/view.html
{% extends "allianceauth/base-bs5.html" %}

{% load aa_i18n %}
{% load i18n %}
{% load evelinks %}

{% get_current_language as LANGUAGE_CODE %}

{% block page_title %}
    {% translate "Structure Timer Management" %}
{% endblock page_title %}

{% block header_nav_brand %}
    {% translate "Structure Timers" %}
{% endblock header_nav_brand %}


{% block header_nav_collapse_right %}
    {% if perms.auth.timer_management %}
        <li class="nav-item">
            <a class="btn btn-success" href="{% url 'timerboard:add' %}">
                {% translate "Create Structure Timer" %}
            </a>
        </li>
    {% endif %}
{% endblock header_nav_collapse_right %}

{% block content %}
    <div class="allianceauth-timerboard">
        <div class="col-lg-12 text-center mb-3">
            <div class="badge bg-primary text-start">
                <span>{% translate "Current Eve Time:" %}</span>
                <span id="current-time"></span>
            </div>
        </div>

        {% if corp_timers %}
            <div class="card mb-3">
                <div class="card-header">
                    <div class="card-title mb-0">
                        {% translate "Corporation Timers" %}
                    </div>
                </div>

                <div class="card-body">
                    {% include "timerboard/timertable.html" with id="corp-timers" timers=corp_timers %}
                </div>
            </div>
        {% endif %}

        <div class="card mb-3">
            <div class="card-header">
                <div class="card-title mb-0">
                    {% translate "Upcoming Timers" %}
                </div>
            </div>

            <div class="card-body">
                {% if future_timers %}
                    {% include "timerboard/timertable.html" with id="future-timers" timers=future_timers %}
                {% else %}
                    <div class="alert alert-warning text-center">
                        {% translate "No upcoming timers." %}
                    </div>
                {% endif %}
            </div>
        </div>

        <div class="card mb-3">
            <div class="card-header">
                <div class="card-title mb-0">
                    {% translate "Past Timers" %}
                </div>
            </div>

            <div class="card-body">
                {% if past_timers %}
                    {% include "timerboard/timertable.html" with id="past-timers" timers=past_timers %}
                {% else %}
                    <div class="alert alert-warning text-center">
                        {% translate "No past timers." %}
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock content %}

{% block extra_css %}
    {% include "bundles/datatables-css-bs5.html" %}
{% endblock extra_css %}

{% block extra_javascript %}
    {% include "bundles/moment-js.html" with locale=True %}
    {% include "bundles/timers-js.html" %}
    {% include "bundles/datatables-js-bs5.html" %}

    {% get_datatables_language_static LANGUAGE_CODE as DT_LANG_PATH %}

    <script>
        const timers = [
            {% for timer in timers %}
                {
                    'id': {{ timer.id }},
                    'targetDate': moment("{{ timer.eve_time | date:"c" }}"),
                    'expired': false
                },
            {% endfor %}

            {% for timer in corp_timers %}
                {
                    'id': {{ timer.id }},
                    'targetDate': moment("{{ timer.eve_time | date:"c" }}"),
                    'expired': false
                },
            {% endfor %}
        ];

        /**
         * Update a timer
         * @param timer Timer information
         */
        const updateTimer = (timer) => {
            if (timer.targetDate.isAfter(Date.now())) {
                const duration = moment.duration(timer.targetDate - moment(), 'milliseconds');

                document.getElementById("countdown" + timer.id).innerHTML = getDurationString(duration);
            } else {
                timer.expired = true;

                document.getElementById("countdown" + timer.id).innerHTML = "";
            }
        };

        const updateAllTimers = () => {
            const l = timers.length;

            for (let i=0; i < l; ++i) {
                if (timers[i].expired) continue;

                updateTimer(timers[i]);
            }
        };

        /**
         * Set the local time info for the timer
         * @param timer Timer information
         */
        const setLocalTime = (timer) => {
            document.getElementById("localtime" + timer.id).innerHTML = timer.targetDate.format("ddd @ LT");
        };

        /**
         * Set all local time fields
         */
        const setAllLocalTimes = () => {
            const l = timers.length;

            for (let i=0; i < l; ++i) {
                setLocalTime(timers[i]);
            }
        };

        const updateClock = () => {
            document.getElementById("current-time").innerHTML = getCurrentEveTimeString();
        };

        const timedUpdate = () => {
            updateClock();
            updateAllTimers();
        }

        // Set initial values
        setAllLocalTimes();
        timedUpdate();

        // Start timed updates
        setInterval(timedUpdate, 1000);

        $(document).ready(() => {
            const dtOptions = {
                language: {url: '{{ DT_LANG_PATH }}'},
                order: [
                    [4, 'asc']
                ],
            };

            {% if perms.auth.timer_management %}
                dtOptions['columnDefs'] = [
                    { "orderable": false, "targets": 7 }
                ];
            {% endif %}

            $('.allianceauth-timerboard table').each((index, table) => {
                $(table).DataTable(dtOptions);
            });
        });
    </script>
{% endblock extra_javascript %}